from __future__ import annotations

from typing import Any


_STATIC_CHUNKS: list[dict[str, Any]] = [
    {
        "chunk_id": "static:rt-law:safe-distance",
        "source_type": "legal_reference",
        "title": "도로교통법 안전거리 및 전방주시 의무",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "앞차와의 안전거리 및 안전운전 의무",
        "snippet": "뒤차는 앞차가 정지하거나 감속하는 상황에도 충돌을 피할 수 있도록 필요한 거리를 두고 전방을 주시해야 합니다.",
        "plain_summary": "후미추돌 사고에서는 뒤차가 안전거리와 전방주시 의무를 지켰는지가 핵심입니다.",
        "related_reason": "정차 또는 감속 중 뒤에서 충돌한 사고와 직접 관련된 판단 기준입니다.",
        "scenario_tags": ["rear_end", "safe_distance"],
        "keywords": ["후미", "뒤차", "추돌", "안전거리", "정차", "급정거", "rear", "distance"],
        "score": 0.43,
    },
    {
        "chunk_id": "static:fault-guide:rear-end",
        "source_type": "knia_reference",
        "title": "후미추돌 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "정차 또는 감속 차량 뒤에서 충돌한 사고",
        "snippet": "앞차가 정상적으로 정차 또는 감속 중이었다면 뒤차의 안전거리 미확보가 중요하게 검토됩니다.",
        "plain_summary": "후미추돌은 뒤차 책임이 크게 검토되지만, 앞차의 급정거 사유와 정지 위치도 함께 확인합니다.",
        "related_reason": "정차 중 뒤에서 충돌한 사고의 과실비율 판단에 참고할 수 있습니다.",
        "scenario_tags": ["rear_end", "safe_distance"],
        "keywords": ["후미추돌", "정차", "감속", "뒤차", "안전거리", "rear", "stopped"],
        "score": 0.45,
    },
    {
        "chunk_id": "static:rt-law:signal",
        "source_type": "legal_reference",
        "title": "도로교통법 신호 준수 의무",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "교차로 신호와 우선순위 확인",
        "snippet": "교차로 사고에서는 각 차량의 신호 상태, 진입 시점, 우선순위가 중요한 판단 요소입니다.",
        "plain_summary": "신호위반이나 교차로 진입 순서가 다투어지는 사고에서 확인해야 하는 기준입니다.",
        "related_reason": "교차로 또는 신호위반 입력이 있을 때 참고할 수 있는 법률 근거입니다.",
        "scenario_tags": ["signal_violation", "intersection"],
        "keywords": ["교차로", "신호", "좌회전", "우회전", "직진", "우선순위", "intersection", "signal"],
        "score": 0.4,
    },
    {
        "chunk_id": "static:legal:signal-transition-cctv",
        "source_type": "legal_reference",
        "title": "신호 전환과 CCTV 확인 기준",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "교차로 신호 전환과 진입 시점",
        "snippet": "황색·적색 신호 전환 사고에서는 차량 진입 시점, 상대 신호, CCTV 또는 신호 주기 자료를 확인해야 합니다.",
        "plain_summary": "신호 전환 교차로 사고는 충돌 순간 신호만이 아니라 진입 시점과 객관 자료를 함께 봅니다.",
        "related_reason": "상대 신호와 내 신호가 다투어지는 사고에서 추가 확인 근거로 쓸 수 있습니다.",
        "scenario_tags": ["intersection", "signal_violation", "cctv"],
        "keywords": ["신호 전환", "황색 신호", "적색 신호", "상대 신호", "CCTV", "intersection"],
        "score": 0.42,
    },
    {
        "chunk_id": "static:rt-law:lane-change",
        "source_type": "legal_reference",
        "title": "도로교통법 차로변경 주의의무",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "진로변경 전 주변 차량 확인 의무",
        "snippet": "차로를 바꾸는 차량은 방향지시등 사용, 사각지대 확인, 충분한 거리 확보를 통해 다른 차량의 정상 진행을 방해하지 않아야 합니다.",
        "plain_summary": "차선변경 중 사고에서는 변경 차량의 주의의무와 기존 차로 차량의 진행 상태를 함께 확인합니다.",
        "related_reason": "차선변경, 끼어들기, 측면 충돌 입력과 관련된 기준입니다.",
        "scenario_tags": ["lane_change", "turn_signal"],
        "keywords": ["차선", "차로", "진로변경", "끼어들기", "방향지시등", "사각지대", "lane", "merge"],
        "score": 0.42,
    },
    {
        "chunk_id": "static:fault-guide:lane-change",
        "source_type": "knia_reference",
        "title": "차선변경 사고 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "진로변경 차량과 직진 차량의 충돌",
        "snippet": "진로를 변경한 차량과 기존 차로를 직진하던 차량이 충돌한 경우 방향지시등, 진입 거리, 충돌 위치를 봅니다.",
        "plain_summary": "차선변경 사고는 변경 차량의 주의의무 위반 여부와 직진 차량의 회피 가능성이 함께 검토됩니다.",
        "related_reason": "차선변경 사고에서 KNIA 계열 기준을 함께 충족하기 위한 참고 근거입니다.",
        "scenario_tags": ["lane_change", "turn_signal"],
        "keywords": ["차선변경", "차로변경", "진로변경", "끼어들기", "방향지시등", "직진 차량", "lane change", "merge"],
        "score": 0.45,
    },
    {
        "chunk_id": "static:rt-law:bicycle-duty",
        "source_type": "legal_reference",
        "title": "자전거 사고 주의의무 확인",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "자전거와 자동차 통행 중 안전확인 의무",
        "snippet": "자동차와 자전거가 충돌한 사고에서는 자전거의 진행 위치, 교차로 진입 방식, 자동차의 전방주시와 안전거리 확보 여부를 함께 확인합니다.",
        "plain_summary": "자전거 사고는 자동차끼리 사고와 달리 취약 교통참여자의 통행 위치와 보호 필요성을 별도로 봅니다.",
        "related_reason": "자전거 탑승자와 차량이 관련된 사고 입력과 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["bicycle", "vulnerable_road_user"],
        "keywords": ["자전거", "차대 자전거", "자전거도로", "교차로 자전거", "취약 교통참여자", "bicycle"],
        "score": 0.43,
    },
    {
        "chunk_id": "static:fault-guide:bicycle",
        "source_type": "knia_reference",
        "title": "자전거 사고 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "자동차와 자전거 충돌 사고의 가감요소",
        "snippet": "자전거 사고에서는 자전거의 주행 위치, 횡단 또는 교차로 진입 여부, 자동차의 전방주시와 속도, 보호 필요성을 함께 봅니다.",
        "plain_summary": "자전거 사고의 과실비율은 자동차 사고 기준을 그대로 붙이기보다 자전거 통행 상황과 보호 필요성을 별도로 확인해야 합니다.",
        "related_reason": "자전거 사고에서 자동차끼리 기준이 잘못 붙는 것을 막기 위한 참고 기준입니다.",
        "scenario_tags": ["bicycle"],
        "keywords": ["자전거", "차대 자전거", "취약 교통참여자", "과실비율", "bicycle"],
        "score": 0.44,
    },
    {
        "chunk_id": "static:legal:bicycle-trigger-rear-end-duty",
        "source_type": "legal_reference",
        "title": "자전거 비접촉 유발과 후미추돌 법률 검토 기준",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "자전거 유발 위험 회피 후 정차 차량과 후방 차량의 충돌 사고",
        "snippet": "자전거가 비접촉 위험을 만들고 앞차가 급제동한 뒤 후방 차량이 충돌했다면 실제 충돌 대상, 자전거 유발성, 앞차 정차의 불가피성, 뒤차의 반응 시간과 안전거리를 분리해 봐야 합니다.",
        "plain_summary": "비접촉 자전거 유발 사고는 자전거가 실제 충돌 대상인지, 앞차 정차가 불가피했는지, 뒤차가 충분히 반응할 시간이 있었는지를 나누어 판단해야 합니다.",
        "related_reason": "자전거 비접촉 유발, 앞차 급정거, 후방 버스 충돌, 급제동 시간 사유, 안전거리와 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["bicycle", "non_contact_trigger", "rear_end", "front_vehicle_stop_reason", "safe_distance"],
        "keywords": [
            "non-contact bicycle trigger",
            "bicycle induced accident",
            "rear-end after bicycle avoidance",
            "reaction time gap",
            "sudden braking",
            "rear-end bus",
            "truck stopped",
            "front vehicle",
            "stop reason",
            "safe distance",
            "자전거",
            "비접촉 유발",
            "후방 버스",
            "후미추돌",
            "앞차",
            "정차 사유",
            "급제동",
            "급정거",
            "시간적 여유",
            "안전거리",
        ],
        "score": 0.5,
    },
    {
        "chunk_id": "static:knia:bicycle-non-contact-trigger",
        "source_type": "knia_reference",
        "title": "자전거 비접촉 유발 사고 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "비접촉 자전거 유발과 후속 추돌 사고",
        "snippet": "자전거의 갑작스러운 진입이나 회피 행동이 앞차의 급정거와 뒤차 추돌로 이어진 경우 자전거 유발성, 앞차의 회피 필요성, 뒤차 안전거리 확보 여부를 함께 봅니다.",
        "plain_summary": "자전거가 직접 충돌하지 않았더라도 사고를 유발했다면 자전거 관련 기준과 후미추돌 기준을 함께 검토해야 합니다.",
        "related_reason": "자전거 유발과 후미추돌 구조가 함께 나타나는 사고에 대한 KNIA 계열 참고 근거입니다.",
        "scenario_tags": ["bicycle", "non_contact_trigger", "rear_end", "safe_distance"],
        "keywords": ["자전거", "비접촉", "유발", "후미추돌", "급정거", "안전거리", "bicycle", "rear-end"],
        "score": 0.48,
    },
    {
        "chunk_id": "static:rt-law:pedestrian-crosswalk",
        "source_type": "legal_reference",
        "title": "보행자·횡단보도 사고 주의의무",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "횡단보도와 보행자 보호의무",
        "snippet": "횡단보도 또는 보행자 사고에서는 차량의 일시정지, 보행자 신호, 시야 확보, 제한속도 준수 여부가 중요합니다.",
        "plain_summary": "보행자 사고는 차량 운전자의 보행자 보호의무와 보행자의 횡단 방식을 함께 검토합니다.",
        "related_reason": "보행자 또는 횡단보도 사고 입력과 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["pedestrian", "crosswalk"],
        "keywords": ["보행자", "횡단보도", "보행자 보호", "일시정지", "crosswalk", "pedestrian"],
        "score": 0.42,
    },
    {
        "chunk_id": "static:fault-guide:pedestrian-crosswalk",
        "source_type": "knia_reference",
        "title": "보행자·횡단보도 사고 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "횡단보도 보행자와 차량 충돌",
        "snippet": "보행자 사고에서는 횡단보도 위치, 보행자 신호, 차량의 일시정지와 감속 여부, 시야 확보 여부를 함께 봅니다.",
        "plain_summary": "횡단보도 주변 보행자 사고는 차량의 보호의무가 강하게 검토되며 보행자의 횡단 방식도 함께 확인합니다.",
        "related_reason": "보행자 또는 횡단보도 사고와 직접 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["pedestrian", "crosswalk"],
        "keywords": ["보행자", "횡단보도", "보행자 보호", "일시정지", "보행자 신호", "과실비율", "pedestrian", "crosswalk"],
        "score": 0.45,
    },
    {
        "chunk_id": "static:fault-guide:crosswalk-front-stop-rear-end",
        "source_type": "knia_reference",
        "title": "횡단보도 앞 앞차 정차 후 후방추돌 과실 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "도로교통법 및 과실비율 인정기준",
        "article_title": "횡단보도 앞 정차 차량 뒤에서 충돌한 사고",
        "snippet": "횡단보도 앞에서 앞차가 정지한 뒤 후방 추돌이 발생한 경우에도 뒤차의 안전거리 의무가 기본이지만, 앞차 정지 사유, 보행자 신호, 횡단보도 위치, 급정지 여부를 함께 검토해야 합니다.",
        "plain_summary": "횡단보도 앞 정차 후 후방추돌 사고는 뒤차의 안전거리 의무를 기본으로 보되, 앞차 정지 사유와 보행자 신호, 급정지 여부를 함께 확인해야 합니다.",
        "related_reason": "앞차 정차 사유, 횡단보도 위치, 보행자 신호, 안전거리, 후방추돌 여부를 함께 확인해야 하는 사고와 관련됩니다.",
        "scenario_tags": ["rear_end", "crosswalk", "front_vehicle_stop_reason", "safe_distance"],
        "keywords": ["front vehicle", "stop reason", "crosswalk", "pedestrian signal", "rear-end", "safe distance", "sudden braking", "stopped", "앞차", "정차 사유", "횡단보도 앞 정차", "보행자 신호", "후방추돌", "안전거리", "급정거"],
        "score": 0.47,
    },
    {
        "chunk_id": "static:legal:front-vehicle-stop-rear-end-duty",
        "source_type": "legal_reference",
        "title": "앞차 정차 사유와 후방추돌 법률 검토 기준",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법 안전거리·전방주시 의무 참고",
        "article_title": "횡단보도·교차로 앞 정차 차량 뒤에서 충돌한 사고",
        "snippet": "횡단보도나 교차로 앞에서 앞차가 정지했고 뒤차가 충돌한 경우, 뒤차의 안전거리 의무가 기본이지만 앞차 정지 사유, 보행자 신호, 급정거 여부, 정지 예견 가능성을 함께 검토해야 합니다.",
        "plain_summary": "앞차가 왜 멈췄는지와 뒤차가 정지 상황을 예견하고 안전거리를 확보할 수 있었는지를 분리해서 봐야 합니다.",
        "related_reason": "앞차 정차 사유, 횡단보도 위치, 보행자 신호, 급정거 여부, 뒤차 안전거리와 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["rear_end", "front_vehicle_stop_reason", "crosswalk", "safe_distance"],
        "keywords": ["front vehicle", "front vehicle stopped", "stop reason", "vehicle stops", "brakes", "crosswalk", "pedestrian signal", "rear-end", "safe distance", "sudden braking", "앞차", "정차 사유", "횡단보도 앞 정차", "보행자 신호", "후방추돌", "안전거리", "급정거"],
        "score": 0.49,
    },
    {
        "chunk_id": "static:rt-law:school-zone",
        "source_type": "legal_reference",
        "title": "어린이보호구역 사고 주의의무",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "어린이보호구역 제한속도와 어린이 보호의무",
        "snippet": "어린이보호구역 사고에서는 제한속도, 어린이 여부, 보행자 보호의무, 전방주시와 감속 여부가 중점적으로 검토됩니다.",
        "plain_summary": "스쿨존 사고는 일반 사고보다 제한속도와 어린이 보호의무가 더 엄격하게 검토됩니다.",
        "related_reason": "어린이보호구역 또는 어린이 상해 사고 입력과 직접 관련된 기준입니다.",
        "scenario_tags": ["school_zone", "child"],
        "keywords": ["어린이보호구역", "스쿨존", "어린이", "제한속도", "school zone", "child"],
        "score": 0.42,
    },
    {
        "chunk_id": "static:fault-guide:school-zone",
        "source_type": "knia_reference",
        "title": "어린이보호구역 사고 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "어린이보호구역 내 어린이·보행자 사고",
        "snippet": "어린이보호구역 사고에서는 제한속도 준수, 어린이 여부, 횡단보도나 통학로 위치, 전방주시와 감속 여부를 중점적으로 확인합니다.",
        "plain_summary": "스쿨존 사고는 일반 보행자 사고보다 운전자의 주의의무와 속도 준수 여부가 더 엄격하게 검토됩니다.",
        "related_reason": "어린이보호구역 또는 어린이 상해 사고와 직접 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["school_zone", "child", "pedestrian"],
        "keywords": ["어린이보호구역", "스쿨존", "어린이", "제한속도", "보행자 보호", "과실비율", "school zone", "child"],
        "score": 0.45,
    },
    {
        "chunk_id": "static:special-act:criminal",
        "source_type": "legal_reference",
        "title": "교통사고처리 특례법 형사책임 확인",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/교통사고처리특례법",
        "law_name": "교통사고처리 특례법",
        "article_title": "중과실 및 인명피해 확인",
        "snippet": "인명피해, 12대 중과실, 음주운전, 무면허, 도주 여부가 있으면 형사책임 검토가 필요합니다.",
        "plain_summary": "다친 사람이 있거나 중대한 법규 위반이 의심되면 형사책임 가능성을 별도로 확인해야 합니다.",
        "related_reason": "부상, 음주, 무면허, 신호위반, 뺑소니 입력과 관련된 기준입니다.",
        "scenario_tags": ["injury", "reporting_duty", "twelve_gross_negligence"],
        "keywords": ["형사", "신고", "중과실", "부상", "인명피해", "음주", "무면허", "뺑소니", "criminal"],
        "score": 0.41,
    },
    {
        "chunk_id": "static:insurance:process",
        "source_type": "legal_reference",
        "title": "보험 처리 기본 체크리스트",
        "source": "교통사고 법률 설명 자료",
        "law_name": "보험 처리 안내",
        "article_title": "접수번호, 영상, 사진, 진단서 보관",
        "snippet": "보험 접수번호, 블랙박스 원본, 현장 사진, 수리 견적서, 진료 기록을 보관해야 합니다.",
        "plain_summary": "사고 직후에는 증거 보관과 보험 접수 진행 상황을 기록하는 것이 중요합니다.",
        "related_reason": "모든 교통사고에서 보험 접수와 증거 보관에 참고할 수 있는 기준입니다.",
        "keywords": ["보험", "접수", "블랙박스", "사진", "견적", "진단서", "insurance", "claim"],
        "scenario_tags": ["insurance"],
        "score": 0.36,
    },
    {
        "chunk_id": "static:legal:unlit-stopped-vehicle-duty",
        "source_type": "legal_reference",
        "title": "야간 무등화 정차 차량 충돌 법률 검토 기준",
        "source": "교통사고 법률 설명 자료",
        "source_url": "https://www.law.go.kr/법령/도로교통법",
        "law_name": "도로교통법",
        "article_title": "야간 시야 확보와 정차 차량 안전조치",
        "snippet": "야간에 등화나 안전조치 없이 정차한 차량과 충돌했다면 정차 위치, 비상등·삼각대 등 안전조치, 제한속도, 시야 확보와 회피 가능성을 함께 검토합니다.",
        "plain_summary": "무등화 정차 차량 사고는 단순 후미추돌로만 보지 않고 정차 차량의 안전조치와 운전자의 야간 시야·속도·회피 가능성을 나누어 봐야 합니다.",
        "related_reason": "야간, 무등화, 정차 차량, 시야 제한, 회피 가능성 입력과 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["stopped_vehicle", "night", "visibility", "speed_limit", "avoidability"],
        "keywords": [
            "unlit stopped vehicle",
            "night visibility",
            "speed limit",
            "avoidability",
            "analysis",
            "stopped vehicle",
            "무등화",
            "야간",
            "정차 차량",
            "시야",
            "제한속도",
            "회피 가능성",
            "비상등",
        ],
        "score": 0.49,
    },
    {
        "chunk_id": "static:knia:unlit-stopped-vehicle",
        "source_type": "knia_reference",
        "title": "야간 무등화 정차 차량 충돌 과실비율 참고 기준",
        "source": "과실비율 인정기준 참고 자료",
        "law_name": "도로교통법 및 과실비율 인정기준",
        "article_title": "야간 등화 없는 정차 차량과 충돌한 사고",
        "snippet": "야간에 등화 없이 정차한 차량을 충돌한 사고는 정차 차량의 등화 상태, 정차 위치, 제한속도, 시야와 회피 가능성이 핵심 가감요소입니다.",
        "plain_summary": "무등화 정차 차량 사고는 운전자의 전방주시와 정차 차량의 안전조치 미흡을 함께 검토해야 합니다.",
        "related_reason": "무등화 정차 차량, 야간 시야, 속도, 회피 가능성을 따져야 하는 사고와 관련됩니다.",
        "scenario_tags": ["stopped_vehicle", "night", "visibility", "speed_limit", "avoidability"],
        "keywords": ["unlit stopped vehicle", "night visibility", "speed limit", "avoidability", "무등화", "야간", "정차 차량", "회피 가능성"],
        "score": 0.47,
    },
]


def retrieve_static_legal_chunks(query: str, limit: int = 5) -> list[dict[str, Any]]:
    q = (query or "").lower()
    ranked: list[tuple[int, float, dict[str, Any]]] = []
    for item in _STATIC_CHUNKS:
        keyword_hits = sum(1 for k in item["keywords"] if str(k).lower() in q)
        tag_hits = sum(1 for tag in item.get("scenario_tags", []) if str(tag).lower() in q)
        score = float(item["score"]) + keyword_hits * 0.04 + tag_hits * 0.03
        payload = {k: v for k, v in item.items() if k != "keywords"} | {"score": round(score, 3)}
        payload.setdefault("source_family", "static_fallback")
        payload.setdefault("retrieval_note", "static_fallback")
        payload.setdefault("display_priority", 90)
        ranked.append((keyword_hits + tag_hits, score, payload))
    max_hits = max((hits for hits, _, _ in ranked), default=0)
    if max_hits > 0:
        ranked = [item for item in ranked if item[0] > 0]
    ranked.sort(key=lambda x: (x[0], x[1]), reverse=True)
    return [x[2] for x in ranked[: max(1, limit)]]
