from __future__ import annotations

from typing import Any


_STATIC_CHUNKS: list[dict[str, Any]] = [
    {
        "chunk_id": "static:rt-law:safe-distance",
        "title": "도로교통법 안전거리 유지 의무",
        "source": "교통사고 법률 설명 자료",
        "law_name": "도로교통법",
        "article_title": "앞차와의 안전거리 및 전방주시 의무",
        "snippet": "뒤차는 앞차와 안전거리를 유지하고 전방 상황에 맞춰 속도를 줄일 주의의무가 있습니다.",
        "plain_summary": "후미추돌 사고에서는 뒤차가 안전거리를 지켰는지와 전방주시를 했는지가 핵심입니다.",
        "related_reason": "정차 또는 감속 중 뒤에서 추돌된 사고와 직접 관련된 확인 기준입니다.",
        "scenario_tags": ["rear_end", "safe_distance"],
        "keywords": ["후미", "뒤차", "추돌", "안전거리", "정차", "급정거", "rear", "distance"],
        "score": 0.39,
    },
    {
        "chunk_id": "static:rt-law:signal",
        "title": "도로교통법 신호 준수 의무",
        "source": "교통사고 법률 설명 자료",
        "law_name": "도로교통법",
        "article_title": "교차로 신호 및 우선권 확인",
        "snippet": "교차로 사고에서는 각 차량의 신호 상태, 진입 시점, 우선권이 중요한 판단 요소입니다.",
        "plain_summary": "신호위반이나 선진입 여부가 다투어지는 사고에서 확인해야 하는 기준입니다.",
        "related_reason": "교차로 또는 신호위반 입력이 있을 때 참고할 수 있는 기준입니다.",
        "scenario_tags": ["signal_violation", "intersection"],
        "keywords": ["교차로", "신호", "좌회전", "우회전", "직진", "우선권", "intersection", "signal"],
        "score": 0.38,
    },
    {
        "chunk_id": "static:rt-law:lane-change",
        "title": "도로교통법 차로변경 주의의무",
        "source": "교통사고 법률 설명 자료",
        "law_name": "도로교통법",
        "article_title": "진로변경 시 주변 차량 확인 의무",
        "snippet": "차로를 바꾸는 차량은 방향지시등 사용, 사각지대 확인, 충분한 거리 확보가 필요합니다.",
        "plain_summary": "차선변경 중 사고에서는 변경 차량이 주변 차량을 충분히 확인했는지가 핵심입니다.",
        "related_reason": "차선변경, 끼어들기, 측면 충돌 입력과 관련된 기준입니다.",
        "scenario_tags": ["lane_change", "turn_signal"],
        "keywords": ["차선", "차로", "진로", "변경", "끼어들", "방향지시등", "사각지대", "lane", "merge"],
        "score": 0.38,
    },
    {
        "chunk_id": "static:special-act:criminal",
        "title": "교통사고처리 특례법 형사책임 확인",
        "source": "교통사고 법률 설명 자료",
        "law_name": "교통사고처리 특례법",
        "article_title": "중과실 및 인명피해 확인",
        "snippet": "인명피해, 12대 중과실, 도주 여부가 있으면 형사책임 검토가 필요합니다.",
        "plain_summary": "다친 사람이 있거나 중대한 법규 위반이 의심되면 신고와 형사책임 여부를 확인해야 합니다.",
        "related_reason": "부상, 음주, 무면허, 신호위반, 뺑소니 입력과 관련된 기준입니다.",
        "scenario_tags": ["injury", "reporting_duty", "twelve_gross_negligence"],
        "keywords": ["형사", "신고", "중과실", "부상", "인명피해", "음주", "무면허", "뺑소니", "criminal"],
        "score": 0.41,
    },
    {
        "chunk_id": "static:criminal-law:injury",
        "title": "형법상 과실치상 검토 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "형법",
        "article_title": "업무상 과실과 상해 발생 여부",
        "snippet": "사고로 사람이 다친 경우 주의의무 위반, 예견 가능성, 인과관계를 확인해야 합니다.",
        "plain_summary": "부상자가 있는 사고에서는 치료 기록과 사고 경위를 함께 확인해야 합니다.",
        "related_reason": "대인 접수나 진단서가 필요한 사고와 관련된 기준입니다.",
        "scenario_tags": ["injury"],
        "keywords": ["부상", "상해", "진단서", "대인", "치료", "injury"],
        "score": 0.37,
    },
    {
        "chunk_id": "static:rt-law:bicycle-duty",
        "title": "자전거 사고 주의의무 확인",
        "source": "교통사고 법률 설명 자료",
        "law_name": "도로교통법",
        "article_title": "자전거와 자동차 통행 중 안전확인 의무",
        "snippet": "자전거와 자동차가 충돌한 사고에서는 자전거의 진행 위치, 교차로 진입 방식, 자동차의 전방주시와 안전거리 확보 여부를 함께 확인해야 합니다.",
        "plain_summary": "자전거 사고는 자동차끼리 사고와 다르게 취약 교통참여자 여부와 통행 위치를 따로 확인해야 합니다.",
        "related_reason": "자전거 탑승 중 차량과 충돌했다는 입력과 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["bicycle", "vulnerable_road_user"],
        "keywords": ["자전거", "차대 자전거", "자전거도로", "교차로 자전거", "취약 교통참여자", "bicycle"],
        "score": 0.41,
    },
    {
        "chunk_id": "static:fault-guide:bicycle",
        "title": "자전거 사고 과실비율 참고 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "자동차와 자전거 충돌 사고의 가감요소",
        "snippet": "차대 자전거 사고에서는 자전거의 주행 위치, 횡단 또는 교차로 진입 여부, 자동차의 전방주시와 속도, 취약 교통참여자 보호 필요성을 함께 봅니다.",
        "plain_summary": "자전거 사고의 과실비율은 자동차 사고 기준을 그대로 쓰기보다 자전거 통행 상황과 보호 필요성을 별도로 확인해야 합니다.",
        "related_reason": "자전거 사고에서 자동차끼리 차선변경 기준이 잘못 붙는 것을 막기 위한 참고 기준입니다.",
        "scenario_tags": ["bicycle"],
        "keywords": ["자전거", "차대 자전거", "취약 교통참여자", "과실비율", "bicycle"],
        "score": 0.42,
    },
    {
        "chunk_id": "static:rt-law:pedestrian-crosswalk",
        "title": "보행자·횡단보도 사고 주의의무",
        "source": "교통사고 법률 설명 자료",
        "law_name": "도로교통법",
        "article_title": "횡단보도와 보행자 보호의무",
        "snippet": "횡단보도 또는 보행자 사고에서는 차량의 일시정지, 보행자 신호, 시야 확보, 제한속도 준수 여부가 중요한 판단 요소입니다.",
        "plain_summary": "보행자 사고는 차량 운전자의 보행자 보호의무와 보행자의 횡단 방식이 함께 검토됩니다.",
        "related_reason": "보행자 또는 횡단보도 사고 입력과 직접 관련된 법률 검토 기준입니다.",
        "scenario_tags": ["pedestrian", "crosswalk"],
        "keywords": ["보행자", "횡단보도", "보행자 보호", "일시정지", "crosswalk", "pedestrian"],
        "score": 0.4,
    },
    {
        "chunk_id": "static:rt-law:school-zone",
        "title": "어린이보호구역 사고 주의의무",
        "source": "교통사고 법률 설명 자료",
        "law_name": "도로교통법",
        "article_title": "어린이보호구역 제한속도와 어린이 보호의무",
        "snippet": "어린이보호구역 사고에서는 제한속도, 어린이 여부, 보행자 보호의무, 전방주시와 감속 여부를 중점적으로 확인해야 합니다.",
        "plain_summary": "스쿨존 사고는 일반 사고보다 제한속도와 어린이 보호의무가 더 엄격하게 검토됩니다.",
        "related_reason": "어린이보호구역 또는 어린이 피해 사고 입력과 직접 관련된 기준입니다.",
        "scenario_tags": ["school_zone", "child"],
        "keywords": ["어린이보호구역", "스쿨존", "어린이", "제한속도", "school zone", "child"],
        "score": 0.4,
    },
    {
        "chunk_id": "static:fault-guide:rear-end",
        "title": "후미추돌 과실비율 참고 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "정차 또는 감속 차량을 뒤에서 추돌한 사고",
        "snippet": "정차 또는 정상 감속 중인 앞차를 뒤차가 추돌했다면 일반적으로 뒤차 책임이 크게 검토됩니다.",
        "plain_summary": "피추돌 차량이 정상적으로 정차 중이었다면 뒤차의 안전거리 미확보가 중요한 판단 요소입니다.",
        "related_reason": "정차 중 뒤에서 추돌당한 사고와 직접 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["rear_end", "safe_distance"],
        "keywords": ["후미", "뒤차", "추돌", "정차", "안전거리", "피추돌", "rear", "stopped"],
        "score": 0.43,
    },
    {
        "chunk_id": "static:fault-guide:crosswalk-front-stop-rear-end",
        "source_type": "knia_reference",
        "title": "Crosswalk front vehicle stop reason and rear-end fault guide",
        "source": "KNIA fault ratio reference",
        "law_name": "Road Traffic Act / fault ratio guide",
        "article_title": "Rear-end collision after a front vehicle stops before a crosswalk",
        "snippet": "When a front vehicle stops before a crosswalk and is hit from behind, safe distance remains central, but the stop reason, pedestrian signal, crosswalk position, sudden braking, and whether the stop was foreseeable must be reviewed together.",
        "plain_summary": "횡단보도 앞에서 앞차가 정지한 뒤 후방 추돌이 발생한 사고는 뒷차의 안전거리 의무를 기본으로 보되, 앞차 정지 사유와 보행자 신호, 급정지 여부를 함께 확인해야 합니다.",
        "related_reason": "front vehicle stop reason, crosswalk, pedestrian signal, safe distance, and rear-end collision are directly relevant.",
        "scenario_tags": ["rear_end", "crosswalk", "front_vehicle_stop_reason", "safe_distance"],
        "keywords": [
            "front vehicle",
            "stop reason",
            "crosswalk",
            "pedestrian signal",
            "rear-end",
            "safe distance",
            "sudden braking",
            "stopped",
        ],
        "score": 0.45,
    },
    {
        "chunk_id": "static:fault-guide:intersection",
        "title": "교차로 사고 과실비율 참고 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "교차로 신호와 진입 순서",
        "snippet": "교차로 사고는 신호 준수 여부, 선진입, 시야 확보, 속도 등을 함께 봅니다.",
        "plain_summary": "교차로에서 충돌한 사고라면 신호와 진입 순서가 과실 판단의 핵심입니다.",
        "related_reason": "교차로 또는 신호위반 사고와 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["intersection", "signal_violation"],
        "keywords": ["교차로", "신호", "선진입", "속도", "우선권", "intersection"],
        "score": 0.42,
    },
    {
        "chunk_id": "static:fault-guide:lane-change",
        "title": "차선변경 사고 과실비율 참고 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "진로변경 차량과 직진 차량의 충돌",
        "snippet": "진로를 변경하는 차량은 방향지시등 사용, 후방·측방 확인, 안전한 차로 변경 가능 여부를 확인해야 합니다.",
        "plain_summary": "차선변경 사고에서는 차선을 바꾼 차량과 기존 차로를 진행하던 차량의 위치와 방향지시등 사용 여부가 과실 판단의 핵심입니다.",
        "related_reason": "상대 또는 내 차량이 차선변경 중 충돌한 사고와 직접 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["lane_change", "turn_signal"],
        "keywords": ["차선변경", "차로변경", "진로변경", "끼어들기", "방향지시등", "직진 차량", "lane change", "merge"],
        "score": 0.43,
    },
    {
        "chunk_id": "static:fault-guide:pedestrian-crosswalk",
        "title": "보행자·횡단보도 사고 과실비율 참고 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "횡단보도 보행자와 차량 충돌",
        "snippet": "보행자 사고에서는 횡단보도 위치, 보행자 신호, 차량의 일시정지와 감속 여부, 시야 확보 여부를 함께 봅니다.",
        "plain_summary": "횡단보도 주변 보행자 사고는 차량의 보행자 보호의무가 강하게 검토되며 보행자의 횡단 방식도 함께 확인합니다.",
        "related_reason": "보행자 또는 횡단보도 사고와 직접 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["pedestrian", "crosswalk"],
        "keywords": ["보행자", "횡단보도", "보행자 보호", "일시정지", "보행자 신호", "과실비율", "pedestrian", "crosswalk"],
        "score": 0.43,
    },
    {
        "chunk_id": "static:fault-guide:school-zone",
        "title": "어린이보호구역 사고 과실비율 참고 기준",
        "source": "교통사고 법률 설명 자료",
        "law_name": "과실비율 인정기준",
        "article_title": "어린이보호구역 내 어린이·보행자 사고",
        "snippet": "어린이보호구역 사고에서는 제한속도 준수, 어린이 여부, 횡단보도나 통학로 위치, 전방주시와 감속 여부를 중점적으로 확인합니다.",
        "plain_summary": "스쿨존 사고는 일반 보행자 사고보다 운전자 주의의무와 속도 준수 여부가 더 엄격하게 검토됩니다.",
        "related_reason": "어린이보호구역 또는 어린이 피해 사고와 직접 관련된 과실비율 참고 기준입니다.",
        "scenario_tags": ["school_zone", "child", "pedestrian"],
        "keywords": ["어린이보호구역", "스쿨존", "어린이", "제한속도", "보행자 보호", "과실비율", "school zone", "child"],
        "score": 0.43,
    },
    {
        "chunk_id": "static:insurance:process",
        "title": "보험 처리 기본 체크리스트",
        "source": "교통사고 법률 설명 자료",
        "law_name": "보험 처리 안내",
        "article_title": "접수번호, 영상, 사진, 진단서 보관",
        "snippet": "보험 접수번호, 블랙박스 원본, 현장 사진, 수리 견적서, 진료 기록을 확보해야 합니다.",
        "plain_summary": "사고 직후에는 증거 보관과 보험 접수 진행 상황을 기록해 두는 것이 중요합니다.",
        "related_reason": "모든 교통사고에서 보험 접수와 증거 보관에 참고할 수 있는 기준입니다.",
        "keywords": ["보험", "접수", "블랙박스", "사진", "견적", "진단서", "insurance", "claim"],
        "score": 0.36,
    },
    {
        "chunk_id": "static:knia:centerline-obstacle",
        "source_type": "knia_reference",
        "title": "Centerline obstacle avoidance fault guide",
        "source": "KNIA fault ratio reference",
        "law_name": "Road Traffic Act / fault ratio guide",
        "article_title": "Centerline crossing caused by parked vehicle or road obstacle",
        "snippet": "When a vehicle crosses the centerline to avoid a parked vehicle or obstacle, the centerline crossing reason, stop position, oncoming vehicle visibility, and avoidability must be reviewed separately.",
        "plain_summary": "중앙선 침범 사고라도 주차 차량 회피, 정차 여부, 마주오던 차량의 회피 가능성에 따라 책임 범위가 달라질 수 있습니다.",
        "related_reason": "centerline obstacle avoidance and oncoming collision require separate fault assessment.",
        "scenario_tags": ["centerline", "stopped_vehicle", "oncoming_vehicle"],
        "keywords": [
            "centerline",
            "centerline crossing",
            "centerline obstacle avoidance",
            "oncoming vehicle collision",
            "parked vehicle",
            "secondary collision",
            "중앙선",
            "중앙선 침범",
            "주차 차량",
            "마주오던 차량",
            "후속 추돌",
        ],
        "score": 0.44,
    },
    {
        "chunk_id": "static:knia:unlit-stopped-vehicle",
        "source_type": "knia_reference",
        "title": "Unlit stopped vehicle visibility and rear-end fault guide",
        "source": "KNIA fault ratio reference",
        "law_name": "Road Traffic Act / fault ratio guide",
        "article_title": "Rear-end collision into an unlit stopped vehicle at night",
        "snippet": "For a night collision into an unlit stopped vehicle, visibility, lighting state, stop location, speed, and whether the collision was avoidable at the lawful speed are key adjustment factors.",
        "plain_summary": "무등화 정차 차량 사고는 단순 후방 추돌 원칙만으로 판단하지 않고 야간 시인성, 정차 위치, 속도별 회피 가능성을 함께 봐야 합니다.",
        "related_reason": "unlit stopped vehicle, night visibility, speed, and avoidability are directly relevant.",
        "scenario_tags": ["stopped_vehicle", "visibility", "rear_end", "speed"],
        "keywords": [
            "unlit stopped vehicle",
            "stealth stopped vehicle",
            "night visibility",
            "avoidability analysis",
            "speed limit",
            "rear-end",
            "무등화",
            "스텔스 차량",
            "야간 시인성",
            "회피 가능성",
            "속도위반",
        ],
        "score": 0.45,
    },
    {
        "chunk_id": "static:legal:centerline-obstacle-duty",
        "source_type": "legal_reference",
        "title": "Centerline obstacle avoidance legal duty guide",
        "source": "Traffic accident legal reference",
        "law_name": "Road Traffic Act / safe driving duty reference",
        "article_title": "Centerline crossing caused by obstacle and oncoming vehicle collision",
        "snippet": "A centerline crossing caused by a parked vehicle or road obstacle should be reviewed with the crossing reason, stop position, oncoming vehicle visibility, and avoidability instead of treating centerline crossing alone as the final result.",
        "plain_summary": "For centerline obstacle avoidance crashes, separate the reason for crossing, whether the vehicle stopped, and whether the oncoming vehicle could avoid the collision.",
        "related_reason": "centerline obstacle avoidance, oncoming collision, stopped position, and secondary collision legal duty review.",
        "scenario_tags": ["centerline", "oncoming_vehicle", "stopped_vehicle", "avoidability"],
        "keywords": [
            "centerline",
            "centerline crossing",
            "centerline obstacle avoidance",
            "oncoming vehicle collision",
            "parked vehicle",
            "secondary collision",
            "avoidability",
            "safe driving duty",
            "Road Traffic Act",
            "legal duty",
        ],
        "score": 0.48,
    },
    {
        "chunk_id": "static:legal:unlit-stopped-vehicle-duty",
        "source_type": "legal_reference",
        "title": "Unlit stopped vehicle visibility legal duty guide",
        "source": "Traffic accident legal reference",
        "law_name": "Road Traffic Act / criminal-civil avoidability reference",
        "article_title": "Night rear-end collision into unlit stopped vehicle",
        "snippet": "A night rear-end collision into an unlit stopped vehicle requires separate review of visibility, lighting, stop location, speed, and whether the collision was avoidable at lawful speed.",
        "plain_summary": "For unlit stopped vehicle cases, distinguish criminal negligence, civil fault ratio, and insurance handling; speeding is relevant but should not override avoidability analysis by itself.",
        "related_reason": "unlit stopped vehicle, night visibility, speed, avoidability, fatality, and criminal/civil split legal review.",
        "scenario_tags": ["stopped_vehicle", "visibility", "rear_end", "speed", "criminal_liability"],
        "keywords": [
            "unlit stopped vehicle",
            "stealth stopped vehicle",
            "night visibility",
            "avoidability analysis",
            "speed limit",
            "speeding",
            "rear-end",
            "fatal traffic accident",
            "criminal liability",
            "civil fault ratio",
            "Road Traffic Act",
        ],
        "score": 0.49,
    },
    {
        "chunk_id": "static:legal:speed-avoidability-criminal-civil",
        "source_type": "legal_reference",
        "title": "Speeding, avoidability, and criminal/civil liability split",
        "source": "Traffic accident legal reference",
        "law_name": "Road Traffic Act / Criminal negligence reference",
        "article_title": "Speed violation does not alone decide avoidability or civil fault ratio",
        "snippet": "When speed is disputed, the analysis should distinguish criminal negligence, civil fault ratio, and insurance handling. Avoidability at legal speed can be more important than the fact of speeding alone.",
        "plain_summary": "속도위반은 불리한 요소지만, 제한속도 주행 시에도 피할 수 없었는지에 대한 감정 결과가 형사와 민사 판단 모두에서 중요합니다.",
        "related_reason": "speeding, avoidability expert analysis, fatal accident, criminal/civil split.",
        "scenario_tags": ["speed", "fatality", "criminal_liability", "civil_fault"],
        "keywords": [
            "speeding",
            "speed limit",
            "avoidability analysis",
            "fatal traffic accident",
            "criminal liability",
            "civil fault ratio",
            "insurance handling",
            "속도위반",
            "회피 가능성",
            "사망 사고",
            "형사",
            "민사",
            "보험",
        ],
        "score": 0.43,
    },
    {
        "chunk_id": "static:knia:bicycle-non-contact-trigger",
        "source_type": "knia_reference",
        "title": "Non-contact bicycle trigger and rear-end response guide",
        "source": "KNIA fault ratio reference",
        "law_name": "Road Traffic Act / fault ratio guide",
        "article_title": "Bicycle-induced non-contact accident followed by rear-end collision",
        "snippet": "When a bicycle creates a non-contact hazard and a vehicle stops or brakes before being hit from behind, the trigger party, following vehicle safe distance, lane change, sudden braking, and reaction time must be separated.",
        "plain_summary": "자전거 비접촉 유발 사고는 직접 충돌 차량만 보지 말고 유발 원인, 트럭 정지의 불가피성, 후방 차량 안전거리와 대응 시간을 분리해야 합니다.",
        "related_reason": "non-contact bicycle trigger, rear-end bus collision, sudden braking, and time gap are directly relevant.",
        "scenario_tags": ["bicycle", "non_contact_trigger", "rear_end", "safe_distance"],
        "keywords": [
            "non-contact bicycle trigger",
            "bicycle induced accident",
            "rear-end after bicycle avoidance",
            "reaction time gap",
            "sudden braking",
            "safe distance",
            "자전거",
            "비접촉 유발",
            "후방 추돌",
            "급제동",
            "시간적 여유",
        ],
        "score": 0.45,
    },
    {
        "chunk_id": "static:legal:signal-transition-cctv",
        "source_type": "legal_reference",
        "title": "Signal transition and CCTV verification guide",
        "source": "Traffic accident legal reference",
        "law_name": "Road Traffic Act",
        "article_title": "Intersection signal transition and entry timing",
        "snippet": "For yellow/red signal transition crashes, the vehicle entry timing, opponent signal phase, and CCTV or signal-cycle evidence should be confirmed before assigning a final fault ratio.",
        "plain_summary": "신호 전환 교차로 사고는 충돌 순간 신호만으로 단정하지 않고 진입 시점, 상대 신호, CCTV 또는 신호 주기 자료를 확인해야 합니다.",
        "related_reason": "signal transition, opponent signal, and CCTV are decisive facts.",
        "scenario_tags": ["intersection", "signal_violation", "cctv"],
        "keywords": [
            "signal transition",
            "yellow signal",
            "red light",
            "opponent signal",
            "CCTV",
            "intersection",
            "신호 전환",
            "황색 신호",
            "적색 신호",
            "상대 신호",
            "CCTV",
        ],
        "score": 0.42,
    },
]


def retrieve_static_legal_chunks(query: str, limit: int = 5) -> list[dict[str, Any]]:
    q = (query or "").lower()
    ranked: list[tuple[int, float, dict[str, Any]]] = []
    for item in _STATIC_CHUNKS:
        keyword_hits = sum(1 for k in item["keywords"] if str(k).lower() in q)
        score = float(item["score"]) + keyword_hits * 0.04
        payload = {k: v for k, v in item.items() if k != "keywords"} | {"score": round(score, 3)}
        ranked.append((keyword_hits, score, payload))
    max_hits = max((hits for hits, _, _ in ranked), default=0)
    if max_hits > 0:
        ranked = [item for item in ranked if item[0] > 0]
    ranked.sort(key=lambda x: (x[0], x[1]), reverse=True)
    return [x[2] for x in ranked[: max(1, limit)]]
